# Generated by Django 3.1.3 on 2022-05-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220529_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='courses',
            new_name='course',
        ),
    ]
