# Generated by Django 3.1.3 on 2022-05-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20220529_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='status',
            new_name='is_correct',
        ),
    ]
